### ISSUE TITLE
Context not added

### ISSUE THREAD

**Issue by ANastasiosDF** [DirectDefense/SuperSerial-Active#1]
Hi guys.After the connection of node ,I receive the the message that heartbeat request was succesful.However, i do not receive any upload output like this on image
https://www.directdefense.com/wp-content/uploads/2015/12/9-node-output-messages.png
NO GET requests or downloads attempts after the connection.

I use the same machine for node and burp suite.

**Comment by DirectDefense** [comment]
Hi ANastasiosDF, thanks for reporting an issue.

The messages shown in the screenshot you linked are caused by an Active Scan process being run on a suspected vulnerable URL. First, the base request/response are checked for certain conditions, and if the correct conditions are detected then an extra scan check is added to the Active Scan to check for a Java Deserialization vulnerability. When the check begins, a new context is created on the Node by the Active Scan process and the check(s) are executed. Are you performing an active scan on a URL?

If you are performing an Active Scan, are there any alerts showing up from SuperSerial-Active in the Alerts tab? Under the Extender Tab, is there any output in the Errors tab for SuperSerial-Active? This information will help narrow down what could be the problem.

Thanks.

**Comment by ANastasiosDF** [comment]
Hi 
Thank you for yours fast reply.I really appreciate that. I am performing an active scan on a URL. There are not any alerts or errors in alert tab or output. The URL-target 90% is clear. My main issue and question is that the active scan is completed/finished from Burp Suite and in my CMD i do not have any updates as in your screen-shot ,only that the Heartbeat request was successful.

**Comment by DirectDefense** [comment]
Would it be possible for you to provide the base request/response that you are performing an active scan on? From the information you provided above, it sounds like the base request/response being scanned are not detected by SuperSerial-Active as having the correct conditions to be tested for a Java Deserialization vulnerability. If we know what the base request/response that you are using look like, we can figure out if there is a bug in the condition-checking logic. Thanks.

**Comment by DirectDefense** [comment]
Hi ANastasiosDF. The latest release of this extender (0.3) contains a new option: scan all parameters. This option automatically tests for a deserialization vulnerability in every request parameter that is natively detected by Burp. If you are still having issues, this setting should solve them. Closing this issue for now, please open a new issue if you are still having issues.
